### ISSUE TITLE
Finding is a

### ISSUE THREAD

**Issue by ksuess** [collective/collective.es.plone#2]
* Plain vanilla Plone
* ElasticSearch running
(It's magic how the stuff gets into ElasticSearch indices, but it does: Kibana shows a plone-portal_catalog index.)
* ingest running with `./bin/celery -A collective.elastic.ingest.celery.app worker -l info`
* redis running with `redis-server /usr/local/etc/redis.conf`

maybe

    ELASTICSEARCH_INDEX plone

should read

    ELASTICSEARCH_INDEX plone-portal_catalog

Content is editable in Plone but

```
 % ./bin/celery -A collective.elastic.ingest.celery.app worker -l info
 
 -------------- celery@Katjas-Mac-Mini.local v5.0.2 (singularity)
--- ***** ----- 
-- ******* ---- macOS-10.15.7-x86_64-i386-64bit 2020-11-27 19:05:07
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         collective.elastic.ingest:0x10a2f60d0
- ** ---------- .> transport:   redis://localhost:6379/0
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . collective.elastic.ingest.index
  . collective.elastic.ingest.unindex

[2020-11-27 19:05:07,965: INFO/MainProcess] Connected to redis://localhost:6379/0
[2020-11-27 19:05:07,980: INFO/MainProcess] mingle: searching for neighbors
[2020-11-27 19:05:09,022: INFO/MainProcess] mingle: all alone
[2020-11-27 19:05:09,035: INFO/MainProcess] celery@Katjas-Mac-Mini.local ready.
[2020-11-27 19:05:09,040: INFO/MainProcess] Received task: collective.elastic.ingest.index[4bcf7d9b-0310-4d37-9d40-bd0f175d80d2]  
[2020-11-27 19:05:09,043: INFO/MainProcess] Received task: collective.elastic.ingest.index[47862a9c-1db0-4a4a-ae4e-c00411e81215]  
[2020-11-27 19:05:09,045: INFO/MainProcess] Received task: collective.elastic.ingest.index[b545288e-08f4-4f53-ba43-97c80e19d90a]  
[2020-11-27 19:05:09,045: INFO/ForkPoolWorker-4] collective.elastic.ingest.index[47862a9c-1db0-4a4a-ae4e-c00411e81215]: fetch content (1) from http://localhost:8080/Plone/testfolder/test-content/testpage-gartnern-im-winter 
[2020-11-27 19:05:09,045: INFO/ForkPoolWorker-2] collective.elastic.ingest.index[4bcf7d9b-0310-4d37-9d40-bd0f175d80d2]: fetch content (1) from http://localhost:8080/Plone/testfolder/test-content/testpage-gartnern-im-winter 
[2020-11-27 19:05:09,048: INFO/MainProcess] Received task: collective.elastic.ingest.index[ecc3fb36-3d57-402f-b661-ac89dfdb5382]  
[2020-11-27 19:05:09,053: INFO/MainProcess] Received task: collective.elastic.ingest.index[7e22dd24-267f-43e9-8ea0-f81972e32cd8]  
[2020-11-27 19:05:09,052: INFO/ForkPoolWorker-1] collective.elastic.ingest.index[b545288e-08f4-4f53-ba43-97c80e19d90a]: fetch content (1) from http://localhost:8080/Plone/testfolder/test-content 
[2020-11-27 19:05:09,052: INFO/ForkPoolWorker-3] collective.elastic.ingest.index[ecc3fb36-3d57-402f-b661-ac89dfdb5382]: fetch content (1) from http://localhost:8080/Plone/testfolder/test-content/testpage-gartnern-im-winter 
[2020-11-27 19:05:09,131: INFO/ForkPoolWorker-1] collective.elastic.ingest.index[b545288e-08f4-4f53-ba43-97c80e19d90a]: fetch full schema from http://localhost:8080/Plone/@cesp-schema





[2020-11-27 19:05:09,133: INFO/ForkPoolWorker-3] collective.elastic.ingest.index[ecc3fb36-3d57-402f-b661-ac89dfdb5382]: fetch full schema from http://localhost:8080/Plone/@cesp-schema
[2020-11-27 19:05:09,158: ERROR/ForkPoolWorker-4] collective.elastic.ingest.index[47862a9c-1db0-4a4a-ae4e-c00411e81215]: Error while writing data to ElasticSearch
Traceback (most recent call last):
  File "/Users/ksuess/RohbergPloneDeployment/rohbergplonedeployment/work/zope/src/collective-elastic-ingest/src/collective/elastic/ingest/celery.py", line 55, in index
    ingest(content, schema, index_name)
  File "/Users/ksuess/RohbergPloneDeployment/rohbergplonedeployment/work/zope/src/collective-elastic-ingest/src/collective/elastic/ingest/ingest.py", line 50, in ingest
    preprocess(content, full_schema)
  File "/Users/ksuess/RohbergPloneDeployment/rohbergplonedeployment/work/zope/src/collective-elastic-ingest/src/collective/elastic/ingest/preprocessing.py", line 112, in preprocess
    action(content, full_schema, ppcfg.get('configuration', {}))
  File "/Users/ksuess/RohbergPloneDeployment/rohbergplonedeployment/work/zope/src/collective-elastic-ingest/src/collective/elastic/ingest/preprocessing.py", line 73, in action_rewrite
    raise ValueError("Source {0} not in content.".format(config['source']))
ValueError: Source @components/rid not in content.
[2020-11-27 19:05:09,161: INFO/ForkPoolWorker-4] Task
```

**Comment by ksuess** [comment]
while thinking about a super creative title, my hand fell down on the send button

**Comment by jensens** [comment]
You may also want to have look at collective.es.index / collective.es.ingestion which is @agitator and my rewrite of this package in a new/more flexible/async way.
